// =============================================================================
//
// Chapel Hill Public Library
//
//		* Horrible.  The table is generated by javascript.
//		* Javascript generated code doesn't get cleaned up by HTML Tidy.   So
//		  we need to manually close the <tr> tags.
//
// =============================================================================

#import "ChapelHillPublicLibrary.h"

@implementation ChapelHillPublicLibrary

// -----------------------------------------------------------------------------
//
// Loans.
//
//		* Data is in the <script> code so don't scanPassHead.
//
// -----------------------------------------------------------------------------
- (void) parseLoans1
{
	[Debug log: @"Parsing loans (Chapel Hill format 1)"];
	NSScanner *scanner		= browser.scanner;
	HTMLElement *element	= nil;
	
	if ([scanner scanNextElementWithName: @"table" attributeKey: @"class" attributeValue: @"patFunc" intoElement: &element recursive: YES])
	{
		// Clean up the HTML
		NSString *value		= [element.value stringByReplacingOccurrencesOfString: @"<tr" withString: @"</tr><tr"];
		NSScanner *scanner	= [NSScanner scannerWithString: value];
		
		NSArray *columns	= [scanner analyseLoanTableColumns];
		NSArray *rows		= [scanner tableWithColumns: columns];
		[self addLoans: rows];
	}
}

// -----------------------------------------------------------------------------
//
// Holds.
//
// -----------------------------------------------------------------------------
- (void) parseHolds1
{
	[Debug log: @"Parsing holds (Chapel Hill format 1)"];
	NSScanner *scanner		= browser.scanner;
	HTMLElement *element	= nil;
	
	if ([scanner scanNextElementWithName: @"table" attributeKey: @"class" attributeValue: @"patFunc" intoElement: &element recursive: YES])
	{
		// Clean up the HTML
		NSString *value		= [element.value stringByReplacingOccurrencesOfString: @"<tr" withString: @"</tr><tr"];
		NSScanner *scanner	= [NSScanner scannerWithString: value];
		
		NSArray *columns	= [scanner analyseHoldTableColumns];
		NSArray *rows		= [scanner tableWithColumns: columns];
		[self addHolds: rows];
	}
}

@end